### ISSUE TITLE
what's the URL of backend admin?

### ISSUE THREAD

**Issue by lamick** [Shuyun123/AppShopService#1]

**Comment by lamick** [comment]
http://xxxxx.com/index.php?m=admin

**Comment by Shuyun123** [comment]
The URL of admin: http://xxxxx.com/index.php/Admin

**Comment by lamick** [comment]
thanks to Shuyun123

**Comment by xiangtongcheng** [comment]
/App/AppShopService/index.php/Home/Index这个路径服务器端没有呀

**Comment by Shuyun123** [comment]
前台路径为：/App/AppShopService/index.php/Home/Index/
后台路径为：/App/AppShopService/index.php/Admin/Index/

**Comment by xiangtongcheng** [comment]
@GET("/App/AppShopService/index.php/Home/Index/{action}")
    Call<ResponseBody> login(@Path("action") String action, @Query("phone") String phoneNumber, @Query("password") String password);请问这个具体实现是在服务端的哪里实现查询数据的代码，谢谢

**Comment by bill198907** [comment]
问下后台账号密码是什么

**Comment by bill198907** [comment]
问下后台账号密码是什么？我看数据库账号应该是admin，但密码作了加密处理；数据库配置是不是改\www\AppShopService-master\Application\Common\Conf\config.php的DB_NAME名就行了？  'DB_HOST'   => '127.0.0.1', // 服务器地址  要改成自己ip吗？wampserver\wamp\apps\phpmyadmin4.6.4\config.inc.php  的$cfg['Servers'][$i]['host'] = '127.0.0.1';也要改成自己ip吗，谢谢

**Comment by Shuyun123** [comment]
数据库根据你本地还是走服务端进行配置，请先看ReadMe.MD

**Comment by Shuyun123** [comment]
> 问下后台账号密码是什么？我看数据库账号应该是admin，但密码作了加密处理；数据库配置是不是改\www\AppShopService-master\Application\Common\Conf\config.php的DB_NAME名就行了？ 'DB_HOST' => '127.0.0.1', // 服务器地址 要改成自己ip吗？wampserver\wamp\apps\phpmyadmin4.6.4\config.inc.php 的$cfg['Servers'][$i]['host'] = '127.0.0.1';也要改成自己ip吗，谢谢

数据库根据你本地还是走服务端进行配置，请先看ReadMe.MD

**Comment by bill198907** [comment]
> > 问下后台账号密码是什么？我看数据库账号应该是admin，但密码作了加密处理；数据库配置是不是改\www\AppShopService-master\Application\Common\Conf\config.php的DB_NAME名就行了？ 'DB_HOST' => '127.0.0.1', // 服务器地址 要改成自己ip吗？wampserver\wamp\apps\phpmyadmin4.6.4\config.inc.php 的$cfg['Servers'][$i]['host'] = '127.0.0.1';也要改成自己ip吗，谢谢
> 
> 数据库根据你本地还是走服务端进行配置，请先看ReadMe.MD


看了，现在就是做完“下载WAMP服务器,配置数据库,导入SQL文件”这一步，项目已经部署了，首页也可以访问，只是我输入账号：admin；密码：123；时页面报错。我不确定是账号问题还是代码数据库配置没修改好问题。“数据库根据你本地还是走服务端进行配置”这个怎么理解呢（我做android的，后台这块不太懂，说的不专业的地方抱歉了）。

**Comment by Shuyun123** [comment]
> > > 问下后台账号密码是什么？我看数据库账号应该是admin，但密码作了加密处理；数据库配置是不是改\www\AppShopService-master\Application\Common\Conf\config.php的DB_NAME名就行了？ 'DB_HOST' => '127.0.0.1', // 服务器地址 要改成自己ip吗？wampserver\wamp\apps\phpmyadmin4.6.4\config.inc.php 的$cfg['Servers'][$i]['host'] = '127.0.0.1';也要改成自己ip吗，谢谢
> > 
> > 
> > 数据库根据你本地还是走服务端进行配置，请先看ReadMe.MD
> 
> 看了，现在就是做完“下载WAMP服务器,配置数据库,导入SQL文件”这一步，项目已经部署了，首页也可以访问，只是我输入账号：admin；密码：123；时页面报错。我不确定是账号问题还是代码数据库配置没修改好问题。“数据库根据你本地还是走服务端进行配置”这个怎么理解呢（我做android的，后台这块不太懂，说的不专业的地方抱歉了）。

数据库本地启动的就走localhost或127.0.0.1。

**Comment by bill198907** [comment]
“数据库本地启动的就走localhost或127.0.0.1。”是指什么呢？\www\AppShopService-master\Application\Common\Conf\config.php的 'DB_HOST' => '127.0.0.1', 这个我没改。但是用账号admin，密码123提示错误：
FILE: D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db\Driver\Mysqli.class.php 　LINE: 45
TRACE
#0 D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db\Driver\Mysqli.class.php(45): E('\xD3\xC9\xD3\xDA\xC4\xBF\xB1\xEA\xBC\xC6\xCB\xE3\xBB\xFA\xBB...')
#1 D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db.class.php(166): Think\Db\Driver\Mysqli->connect()
#2 D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db\Driver\Mysqli.class.php(80): Think\Db->initConnect(false)
#3 D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db\Driver\Mysqli.class.php(209): Think\Db\Driver\Mysqli->query('SHOW COLUMNS FR...')

**Comment by alkaid-ops** [comment]
> “数据库本地启动的就走localhost或127.0.0.1。”是指什么呢？\www\AppShopService-master\Application\Common\Conf\config.php的 'DB_HOST' => '127.0.0.1', 这个我没改。但是用账号admin，密码123提示错误：
> FILE: D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db\Driver\Mysqli.class.php 　LINE: 45
> TRACE
> #0 D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db\Driver\Mysqli.class.php(45): E('\xD3\xC9\xD3\xDA\xC4\xBF\xB1\xEA\xBC\xC6\xCB\xE3\xBB\xFA\xBB...')
> #1 D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db.class.php(166): Think\Db\Driver\Mysqli->connect()
> #2 D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db\Driver\Mysqli.class.php(80): Think\Db->initConnect(false)
> #3 D:\apache\wampserver\wamp\www\AppShopService\ThinkPHP\Library\Think\Db\Driver\Mysqli.class.php(209): Think\Db\Driver\Mysqli->query('SHOW COLUMNS FR...')

你mysql没有对接好，请自行修改AppShopService-master\Application\Common\Conf\config.php
先用phpmyadmin修改mysql root密码为123 再新建utf8mm4类型数据库 数据库名AppService 再导入sql文件utf8格式 基本上就可以了
